In [ ]:
import numpy as np

In [ ]:
array_1D =np.array([[1,2,3,4]])
array_1D.shape


(1, 4)

In [ ]:
#Ending use for dimention
#Size of array


In [ ]:
 array_2D = np.array([[1,2,3],[4,5,6]])
 array_2D.shape


(2, 3)

In [ ]:
array_3D = np.array([[1,2,3],[5,6,7],[8,9,10]])
array_3D.shape
array_3D.dtype


dtype('int64')

In [ ]:
mx_0s = np.zeros(6)
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
mx_0s = np.zeros((6,2))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
mx_1s = np.ones((6,3))
print(mx_1s)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
mx_0s = np.zeros((6,4))
print(mx_1s)
mx_1s.dtype

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


dtype('float64')

In [ ]:
#Arange

In [ ]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr = np.arange(1,11)
reshaped_arr = arr.reshape(2, 5)
print(reshaped_arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
reshaped_arr = arr.reshape(1,10)
print(reshaped_arr)

[[ 1  2  3  4  5  6  7  8  9 10]]


In [ ]:
#Line space

In [ ]:
arr = np.linspace(1,5,4)
print(arr)

[1.         2.33333333 3.66666667 5.        ]


In [ ]:
#Ravel

In [ ]:
arr=np.ravel(arr)
print(arr)

[1.         2.33333333 3.66666667 5.        ]


In [ ]:
#Lstack and Restack

In [ ]:
print('--- Vertical Stacking (np.vstack) ---')

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print('Array 1:', arr1)
print('Array 2:', arr2)


v_stacked_arr = np.vstack((arr1, arr2))
print('\nVertically stacked array (from 1D arrays):\n', v_stacked_arr)

arr3 = np.array([[10, 20, 30]])
arr4 = np.array([[40, 50, 60]])

print('\nArray 3:', arr3)
print('Array 4:', arr4)


v_stacked_arr_2d = np.vstack((arr3, arr4))
print('\nVertically stacked array (from 2D arrays):\n', v_stacked_arr_2d)

--- Vertical Stacking (np.vstack) ---
Array 1: [1 2 3]
Array 2: [4 5 6]

Vertically stacked array (from 1D arrays):
 [[1 2 3]
 [4 5 6]]

Array 3: [[10 20 30]]
Array 4: [[40 50 60]]

Vertically stacked array (from 2D arrays):
 [[10 20 30]
 [40 50 60]]


In [ ]:
print('--- Horizontal Stacking (np.hstack) ---')

arr5 = np.array([1, 2, 3])
arr6 = np.array([4, 5, 6])

print('Array 5:', arr5)
print('Array 6:', arr6)

h_stacked_arr = np.hstack((arr5, arr6))
print('\nHorizontally stacked array (from 1D arrays):\n', h_stacked_arr)
arr7 = np.array([[10, 20], [30, 40]])
arr8 = np.array([[50, 60], [70, 80]])

print('\nArray 7:\n', arr7)
print('\nArray 8:\n', arr8)

h_stacked_arr_2d = np.hstack((arr7, arr8))
print('\nHorizontally stacked array (from 2D arrays):\n', h_stacked_arr_2d)

--- Horizontal Stacking (np.hstack) ---
Array 5: [1 2 3]
Array 6: [4 5 6]

Horizontally stacked array (from 1D arrays):
 [1 2 3 4 5 6]

Array 7:
 [[10 20]
 [30 40]]

Array 8:
 [[50 60]
 [70 80]]

Horizontally stacked array (from 2D arrays):
 [[10 20 50 60]
 [30 40 70 80]]


## More NumPy Mathematical Functions

NumPy provides a comprehensive set of mathematical functions that operate element-wise on arrays. These functions are often much faster than implementing similar operations using Python loops, thanks to NumPy's optimized C implementations.

Let's look at some common examples:

In [ ]:
#Mathematical Function

In [ ]:
# Example array
arr_math = np.array([1, 4, 9, 16, 25])
print('Original Array:', arr_math)

# Square root
print('\nSquare Root (np.sqrt):', np.sqrt(arr_math))

# Exponential
print('Exponential (np.exp):', np.exp(arr_math))

# Logarithm (natural log)
print('Natural Logarithm (np.log):', np.log(arr_math))

# Sine (element-wise)
arr_angles = np.array([0, np.pi/2, np.pi])
print('\nArray of angles (radians):', arr_angles)
print('Sine (np.sin):', np.sin(arr_angles))

# Cosine (element-wise)
print('Cosine (np.cos):', np.cos(arr_angles))

Original Array: [ 1  4  9 16 25]

Square Root (np.sqrt): [1. 2. 3. 4. 5.]
Exponential (np.exp): [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
Natural Logarithm (np.log): [0.         1.38629436 2.19722458 2.77258872 3.21887582]

Array of angles (radians): [0.         1.57079633 3.14159265]
Sine (np.sin): [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine (np.cos): [ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [ ]:
arr1 = np.array([[1, 2, 3], [4,5,6]])
arr2 = np.array([[7, 8, 9], [10,11,12]])

print('Array 1:\n', arr1)
print('Array 2:\n', arr2)

print('\nAddition:\n', arr1 + arr2)
print('\nSubtraction:\n', arr1 - arr2)
print('\nMultiplication:\n', arr1 * arr2)
print('\nDivision:\n', arr1 / arr2)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]

Addition:
 [[ 8 10 12]
 [14 16 18]]

Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]

Multiplication:
 [[ 7 16 27]
 [40 55 72]]

Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


## NumPy Broadcasting

NumPy broadcasting is a powerful mechanism that allows NumPy to work with arrays of different shapes when performing arithmetic operations. It effectively 'stretches' the smaller array across the larger array so that they have compatible shapes without actually making copies of the data.

### How Broadcasting Works:

For two arrays to be compatible for broadcasting, their dimensions must satisfy one of the following conditions, starting from the trailing dimension (rightmost):

1.  **Equal:** The dimensions are equal.
2.  **One is 1:** One of the dimensions is 1.

If these conditions are not met, a `ValueError` is raised, indicating that the arrays are not compatible for broadcasting.

In [ ]:
#Make a brodcasting in depth alone with numpy and array of differcient by 1d and 2d

In [ ]:
print('--- Broadcasting with 1D Arrays (Addition) ---')

arr_1 = np.array([1, 2, 3,4])
arr_2 = np.array([5])
sum_arr = arr_1 + arr_2

print('Array 1:', arr_1)
print('Array 2:', arr_2)

print('\nResult of arr_1 + arr_2 (Broadcasting):', sum_arr)


--- Broadcasting with 2D and 1D Arrays (Addition) ---
Array 1: [1 2 3 4]
Array 2: [5]

Result of arr_1 + arr_2 (Broadcasting): [6 7 8 9]


In [ ]:
print('--------------Broadcasting with 2D array (Addition)----------------')


arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d2 = np.array([[10, 20, 30]])

sum_arr = arr_2d + arr_2d2

print('Array 2D:\n', arr_2d)
print('Array 1D:', arr_2d2)

--------------Broadcasting with 2D array (Addition)----------------
Array 2D:
 [[1 2 3]
 [4 5 6]]
Array 1D: [[10 20 30]]


In [ ]:
print('------------------Broadcasting with 2d and 3d array(addition)------------')

arr_3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr_2D = np.array([[10, 20], [30, 40]])

sum_arr = arr_3D + arr_2D

print('Array 3D:\n', arr_3D)
print('Array 2D:\n', arr_2D)
print('sum_arr:\n', sum_arr)

------------------Broadcasting with 2d and 3d array(addition)------------
Array 3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Array 2D:
 [[10 20]
 [30 40]]
sum_arr:
 [[[11 22]
  [33 44]]

 [[15 26]
  [37 48]]]


In [ ]:
print('-------------Broadcasting 1d*scalar(multiplication)------------')
arr_1 = np.array([1,2,3,4])
scalar = (4)

result_mult = arr_1*scalar
print('Array 1:', arr_1)
print('Scalar:', scalar)
print('\nResult of arr_1 * scalar (Broadcasting):', result_mult)

-------------Broadcasting 1d*scalar(multiplication)------------
Array 1: [1 2 3 4]
Scalar: 4

Result of arr_1 * scalar (Broadcasting): [ 4  8 12 16]


In [ ]:
print('-------------Broadcasting 2d*scalar(multiplication)------------')
arr_2 = np.array([[1, 2, 3], [4, 5, 6]])
scalar =(6)

result_mult = arr_2*scalar
print('Array 2D:\n', arr_2)
print('Scalar:', scalar)
print('\nResult of arr_2 * scalar (Broadcasting):\n', result_mult)

-------------Broadcasting 2d*scalar(multiplication)------------
Array 2D:
 [[1 2 3]
 [4 5 6]]
Scalar: 6

Result of arr_2 * scalar (Broadcasting):
 [[ 6 12 18]
 [24 30 36]]


In [ ]:
print('-------------Broadcasting  3d array*scalar(multiplication)------------')
arr_3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
scalar =(10)
result_mult = arr_3*scalar
print('Array 3D:\n', arr_3)
print('Scalar:', scalar)
print('\nResult of arr_3 * scalar (Broadcasting):\n', result_mult)

-------------Broadcasting  3d array*scalar(multiplication)------------
Array 3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Scalar: 10

Result of arr_3 * scalar (Broadcasting):
 [[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [ ]:
array = np.array ([1,2,4],[-1,-2,-4])



String function

In [ ]:
# Example 1: Convert to uppercase
string_array = np.array(['hello', 'world', 'numpy'])
uppercase_array = np.char.upper(string_array)
print('Original array:', string_array)
print('Uppercase array:', uppercase_array)

# Example 2: Join strings
join_array = np.array([['hello', 'world'], ['python', 'numpy']])
joined_string = np.char.join(' ', join_array) # Join elements within each sub-array
print('\nArray for joining:', join_array)
print('Joined strings:', joined_string)

# Example 3: Check for prefix
prefix_check = np.char.startswith(string_array, 'n')
print('\nCheck for prefix "n" in', string_array, ':', prefix_check)

# Example 4: Replace substring
replace_array = np.char.replace(string_array, 'o', '0')
print('\nOriginal array:', string_array)
print('Array after replacing "o" with "0":', replace_array)


Original array: ['hello' 'world' 'numpy']
Uppercase array: ['HELLO' 'WORLD' 'NUMPY']

Array for joining: [['hello' 'world']
 ['python' 'numpy']]
Joined strings: [['h e l l o' 'w o r l d']
 ['p y t h o n' 'n u m p y']]

Check for prefix "n" in ['hello' 'world' 'numpy'] : [False False  True]

Original array: ['hello' 'world' 'numpy']
Array after replacing "o" with "0": ['hell0' 'w0rld' 'numpy']
